# Generated by Django 5.1.2 on 2024-10-27 12:23

import django.core.validators
import regular_exam_october.authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name must contain letters only.', max_length=40, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(40), regular_exam_october.authors.models.validate_letters_only])),
                ('last_name', models.CharField(help_text='Your last name must contain letters only.', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), regular_exam_october.authors.models.validate_letters_only])),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits.', max_length=6, validators=[regular_exam_october.authors.models.validate_passcode])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
