# Generated by Django 5.0.4 on 2024-10-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_artist_name_alter_album_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Genre Pop'), ('Jazz Music', 'Genre Jazz'), ('R&B Music', 'Genre Rnb'), ('Rock Music', 'Genre Rock'), ('Country Music', 'Genre Country'), ('Dance Music', 'Genre Dance'), ('Hip Hop Music', 'Genre Hip Hop'), ('Other', 'Genre Other')], max_length=30),
        ),
    ]
