# Generated by Django 5.0.4 on 2024-10-08 19:22

import django.core.validators
import exam_prep_my_music_app.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), exam_prep_my_music_app.profiles.validators.validate_username]),
        ),
    ]
