# Generated by Django 5.0.4 on 2024-11-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_approve_posts', 'Can approve posts')]},
        ),
    ]
