# Generated by Django 5.0.4 on 2024-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
